[package]
name = "kueue"
version = "0.2.2"
authors = ["Florian Klemme <mail@florianklemme.de>"]
edition = "2021"
description = "A robust, user-level, work-stealing distributed task scheduler."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.0", features = ["derive"] }
config = "0.13"
console = "0.15"
directories = "4.0"
gethostname = "0.3"
log = "0.4"
names = "0.14"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simple_logger = "2.3"
sysinfo = "0.26"
terminal_size = "0.2"
tokio = { version = "1.21", features = ["full"] }
toml = "0.5"
